"""add regions, user_regions, visibility

Revision ID: 7f699d6c6caf
Revises: 51b27d9ef3d8
Create Date: 2026-10-07 12:40:04.096281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '7f699d6c6caf'
down_revision: Union[str, None] = '51b27d9ef3d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Declare the ENUM object explicitly for PostgreSQL
visibility_enum = postgresql.ENUM('everyone', 'region', 'nobody', name='visibilitylevel')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Create the custom ENUM type in PostgreSQL first
    visibility_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_name'), 'regions', ['name'], unique=True)
    
    op.create_table('user_regions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'region_id')
    )
    
    # 2. Reference the created ENUM object when adding the column
    op.add_column('users', sa.Column('visibility', visibility_enum, server_default='nobody', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'visibility')
    
    # Drop the custom ENUM type after removing the column using it
    visibility_enum.drop(op.get_bind(), checkfirst=True)

    op.drop_table('user_regions')
    op.drop_index(op.f('ix_regions_name'), table_name='regions')
    op.drop_table('regions')
    # ### end Alembic commands ###